### ISSUE TITLE
Code Generation and API ergonomics

### ISSUE THREAD

**Issue by polyfractal** [elastic-rs/elastic#145]
First off, this looks like a great crate!  You've done a huge amount of work, and it looks wonderful!  I'm going to give it shot for a side project soon.  Thanks for making it available :)

I noticed the generated API is a bit redundant in places.  For example, the [Search API](https://kodraus.github.io/rustdoc/elastic_hyper/search/index.html) has two sets of methods: `get_*` and `post_*`, which I presume correspond to the HTTP verb that is used.

It looks like these are generated from [`methods` field in the JSON spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L4).  I just wanted to let you know that these are the "accepted" methods for each endpoint, but they don't have different functionality.  E.g. a search should use GET, but it allows POST because not all clients allow GET + body.  But they both have the same functionality.

I think it might be cleaner if the codegen only created the API for one verb?  Or perhaps added an optional argument that can be used to customize the options at runtime?

Secondly, I noticed that the codegen enumerates out all the possible path options (e.g. `get`, `get_index`, `get_index_type`).  That works, but may make it a bit clunky to use in an automated environment, where your application is dynamically building the request.  It forces the end-user to know what kind of search they want to perform and dispatch accordingly, instead of just setting arguments on the endpoint and firing off a generic search.

Perhaps it could be collapsed to a single endpoint, and the various path components (`index`,`type`) could be wrapped in Options as arguments? 

Anyhow, just some thoughts about ergonomics.  The client looks great as it is, and I'm excited to give it a shot :)

**Comment by KodrAus** [comment]
Hey thanks for checking it out and giving some awesome feedback! My original use-case for the client was for static, hand-crafted calls, so it didn't bother me to need to know the possible parameters at compile-time, plus was easier to implement, and different to [`rs-es`](https://github.com/benashford/rs-es). Having separate endpoints for the possible parameters does save us from having to do a bunch of possible `None` checks, but ultimately those saved nanoseconds are peanuts compared to the milliseconds the request will take.

I'd like to overhaul the codegen, you've pointed out a bunch of places where it falls short which I think are important to address. Right now I'm working on the `types` implementation (I've churned the API a few times, and am about to do it again in a few days unfortunately). So it'll take a bit of time to go through this. If you can't work around the API in the meantime, `rs-es` might be a better fit.

I've opened up a [milestone](https://github.com/KodrAus/elasticsearch-rs/milestone/8) for rethinking the consumer API. Luckily, having a codegen base means it's not too difficult to iterate new client implementations.

**Comment by polyfractal** [comment]
Makes sense!  They are pretty minor cosmetic suggestions anyhow, and it's not too much work for the application to throw a pattern match at the end of building a request to determine which method should be dispatched :)

**Comment by KodrAus** [comment]
@polyfractal I thought you might be interested in an update on how I'm consumer-friendlifying this crate. I've got details in a worked issue [here](https://github.com/elastic-rs/elastic/issues/153).

Essentially, everything is being better organised in a GitHub org, and the current collection of orthogonal libraries I have now are going to be used to create a high-level opinionated client API.

**Comment by polyfractal** [comment]
Neat!  I'm on the road at the moment and only had a chance to skim, but it's looking good!  When I'm home I'll take a closer look :)

**Comment by KodrAus** [comment]
Alrighty! It's been a while, but I think the API ergonomics have improved a lot. You can see some examples [here](https://github.com/elastic-rs/elastic/tree/master/examples). And the [docs](https://docs.rs/elastic/*/elastic/).

There's still more to do though; more real-world examples, more documentation. The type mapping docs are pretty good, but the rest has a long way to go.

With everything split into separate components it'll be easier to support more bespoke or async request pipelines. That's kind of the next phase.

@polyfractal Feel free to re-open this issue if you've got any more feedback.
