### ISSUE TITLE
Question: Iterating results 

### ISSUE THREAD

**Issue by stephanbuys** [elastic-rs/elastic#154]
Hi, I've used your crate successfully to query ES - it works great, do you have any supporting crates (or plans for) to assist with processing the output/returns?

I've spent quite a bit of time over the last few years parsing, iterating over results (aggregations as well as normal search hits), and am about to start playing with implementing an actual rusty Iterator for the results returned by your library. The idea is that it would facilitate hassle-free, fast (zero-copy) processing that can use rust's built in goodness (https://doc.rust-lang.org/beta/std/iter/index.html), as well as something like Rayon (https://github.com/nikomatsakis/rayon).

Would love to get your thought on this, and if its something that you would be interested in as a contribution, where it should be plugged into this eco-system.

Cheers,

**Comment by KodrAus** [comment]
Hi @stephanbuys! That sounds like a great idea. One of the goals of splitting functionality across a bunch of crates here is to let people pick and choose implementations. An efficient parser for Elasticsearch responses is definitely one of those pieces.

There's an [`elastic_types`](https://github.com/elastic-rs/elastic-types) crate that plays nice with `serde`, so I was going to use it for deserialising responses. A more bespoke alternative that doesn't depend on `serde` would also be great.

As for how it would plug in, I'd be thinking about capturing all the information needed to parse a given response, like the endpoint called, http response code and a `Read` to get the body from, and work from that. Some things, like aggregations, depend on data from the request so I guess they'd need to be able to access that somehow. It should be possible to build independently of any particular http library or Elasticsearch requests library.

As an aside, I'm working on a [new implementation](https://github.com/elastic-rs/elastic-requests/issues/1) of `elastic_hyper` that's a bit more ergonomic, but hopefully just as assumption-free. I'd be keen to get some feedback on whether that's on the right track.

Thanks!

**Comment by stephanbuys** [comment]
Hi, why would you like to drop serde? What have you got in mind? (more bespoke alternative)

What data from the requests do you think aggregations depend on? Just interested to hear your thoughts there.

**Comment by KodrAus** [comment]
> why would you like to drop serde?

Ah sorry, let me clarify that point. I've got no problems depending on `serde`, I actually really like it. The point I was trying to make was that whatever works for you for parsing responses, whether that's `serde` or not, is totally cool.

For `serde` specifically, I'm anticipating results that span multiple types could be problematic without the slow intermediate step of parsing hits to a common `Value` type. But an easy solution to that problem is just not include multiple types in your results.

As for aggs, they'd be easier to parse if you knew what type they were, since it's not part of the response. You kind of have to inspect them, or know from the request what type they should be. But you'd be more of an expert in that area than me, my usecase is more around ingest than querying. That's just an observation without actually trying to write a parser for them :)

**Comment by stephanbuys** [comment]
Ok awesome, and your point re the `Value` types are spot-on, I've personally wrestled with it a lot.

Point taken on the `aggs` side, we've gotten in the habit of clearly labelling each aggregation in its `aggregation_name` field. I've also had some success detecting the type of aggregation based on the properties of the objects in the aggregation tree (ie, if there's a `value` field is a simple type, if there's a `avg`, `min` and `max` field you're dealing with `stats` or `extended_stats`, etc) I'll prototype something for discussion sometime next week. But your point are great food for thought.

**Comment by KodrAus** [comment]
Ah interesting, I think infering the kind of aggregation from its shape is how the .NET client currently does it. It sounds pretty tricky though.

I'm keen to see what you come up with! Especially since it's something I haven't given a whole lot of thought previously. If `rs-es` can share the love too that would be ideal.

**Comment by stephanbuys** [comment]
@KodrAus just a heads-up that I've started on this at https://github.com/stephanbuys/elastic-responses, the initial parsing (hybrid strongly typed/dynamic). If you are interested I would be grateful for any feedback, comments on the API, actually anything.

Next up is to build a state machine to traverse the aggregations and emit a row/table based output on each call of `.next()`, ie, each step will be a `serde_json::Value::Object`, but that adds `parent` node information values, flattening the tree into a table (A non-operating example can be seen in `src/reference.rs`. The idea is that this will work well (same as `.hits()`) with rust's built-in iterator adaptors as mentioned above.

**Comment by KodrAus** [comment]
Awesome :+1: It'll be great to be able to parse response types with aggregations nicely.

**Comment by stephanbuys** [comment]
@KodrAus you can have a look at https://github.com/stephanbuys/elastic-responses, the core is in place. Next is some documentation and looking at the integration into `elastic-hyper`

**Comment by stephanbuys** [comment]
@KodrAus You can have a look at https://github.com/stephanbuys/elastic-responses/tree/master/samples/basic for a working example, outstanding is just documentation, polish and getting rid of last remaining `unwrap()` calls.

**Comment by KodrAus** [comment]
@stephanbuys Ah that API looks great! 👍 Sorry for not responding sooner, I was waiting until I had something worthwhile to contribute. What's the plan next? Support for parsing error responses would be interesting.

**Comment by stephanbuys** [comment]
@KodrAus - just a heads up that the crate for `elastic-responses` has been published https://crates.io/crates/elastic_responses (also merged your pull request)

**Comment by KodrAus** [comment]
@stephanbuys Ah great! I can pull it into the [`elastic`](https://github.com/elastic-rs/elastic/blob/master/src/lib.rs) meta package I'm starting to put together.

Are you happy for this issue to be closed?

**Comment by stephanbuys** [comment]
Thanks for the help, sounds good (meta package)

**Comment by KodrAus** [comment]
If you have any questions/suggestions for the meta package please feel free to raise them. I'm also happy to add you as a member to this org if you feel like contributing stuff :)

**Comment by stephanbuys** [comment]
@KodrAus, I'm sure we'll be doing a bunch of things in this space over the next year - so yeah, happy to join. Happy to move elastic-responses to the org too if you want it.

**Comment by KodrAus** [comment]
That one's your decision. I'd certainly welcome it if you wanted to bring it in to the org, but with it up on crates.io it easy for us to consume it as it is.
