### ISSUE TITLE
Move elastic-responses to elastic-rs org

### ISSUE THREAD

**Issue by stephanbuys** [elastic-rs/elastic#161]
Hi @KodrAus, I think it makes most sense to move the repo to the `elastic-rs` org, it was always intended to be a part of that toolchain. Happy if I do so? We can create a new repo and just push into it here, or I can do a 'back-office' transfer of the whole repo. Your choice :-)

**Comment by KodrAus** [comment]
Definitely happy for you to do that :+1: If you do a back-office transfer GitHub will set up redirects for you (or so it says) and will keep the issue and PR history.

But I'm also not fussed on how you bring it in, so whichever way is easiest for you.

**Comment by stephanbuys** [comment]
Done 👍

**Comment by KodrAus** [comment]
Awesome :+1: I might open this back up and go update all the places I've linked `elastic_responses`.

**Comment by KodrAus** [comment]
Ok I've updated some links :+1:
