### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic#167]
`elastic` should offer an async API based on `tokio` that can execute different aspects of the request pipeline as independent futures. So we might have a socket managed by `tokio`, and responses deserialised by some background thread pool.

This depends on either an async release of `hyper` or `reqwest`.

There will also be a few changes needed to the API surface, like making `RequestBuilder` take an `Arc<Client>` instead of an `&Client`.

**Comment by KodrAus** [comment]
Related: #168

**Comment by xrl** [comment]
Why do you think the response should be decode in a background thread pool? Seems a bit overly complicated but maybe I'm misunderstanding how long it would take to decode even a large response.

**Comment by KodrAus** [comment]
You're right, it's possibly overkill and would have to be measured.

I think it's worth looking into though since the time spent deserialising responses on the `tokio` core thread is time not spent processing other `tokio` services.

I'm open to any suggestions though :)

**Comment by xrl** [comment]
If tokio should only do readiness checks/flushing of IO then it does follow that all other work should be done in a CPUPool. I would be very curious to benchmark this situation and provide some info. I think the Tokio ecosystem would be excited to read about the results.

**Comment by KodrAus** [comment]
I think that's definitely a worthwhile thing to do. At least with the `futures_cpupool` crate it's trivial to offload some work onto a background thread, so spiking it out wouldn't be a lot of effort.

I'm mostly thinking about a default, high-level `elastic` API that makes some assumptions on behalf of the user, and one of those might be that you'll benefit from deserialisation on a background thread.

I think it's also important to offer a lower-level API that exposes intermediate results, so you can make a request and get a response, and then go deserialise that response on the thread you're on, or go schedule it somewhere else yourself. The current synchronous API basically already supports that:

```rust
// --- High-level: deserialisation is done for you ---
let response = client.search::<Value>().send()?;


// --- Low-level: you deserialise yourself ---

// Get a HTTP response
let http_res = client.request(some_request).send()?;

// Deserialise the SearchResponse
let response: SearchResponse<Value> = http_res.into_response()?;
```

In an async API that might look like:

```rust
// --- High-level: deserialisation is done for you ---
let response_future = client.search::<Value>().send();


// --- Low-level: you deserialise yourself ---

// Get a future HTTP response
let http_res_future = client.request(some_request).send();

// Get a future deserialised response. Maybe do this on a CPU pool
let deserialise_future = http_res_future.and_then(into_response::<SearchResponse<Value>>);
```

**Comment by KodrAus** [comment]
Hmm, I'm not sure yet how to implement [`tokio_service::Service`](https://docs.rs/tokio-service/0.1.0/tokio_service/trait.Service.html) for this async API, since it accepts many different request types and produces many different response types.

I suppose it could just be:

```rust
impl Service for Client {
    type Request: HttpRequestBuilder;
    type Response: HttpResponseBuilder;
}
```

I'll need to think about it a bit more... It would mean that the client itself is stateless and receives requests as input to send, which isn't a bad thing, but messes up how we do shared parameters right now.

**Comment by KodrAus** [comment]
For implementing async I think there are a few concerns:

- I think we should still offer a first-class synchronous client. If you're not already in an asynchronous context (like a `hyper` server) then having to create a `Core` and execute units of work on it is a bit of a pain
- I don't want to have to repeat builder logic on request types, but also don't want to lose the convenient `send()` method
- It's not trivial to make an asynchronous request act synchronously. `reqwest` does the hard work already in its synchronous `Client` implementation. I'd rather leverage that
- I want a common set of body types to be usable across synchronous and asynchronous requests, like `String`, `Vec<u8>` and their borrowed counterparts
- The asynchronous client will probably offer more switches over the synchronous one. I don't want to be in a situation where users are forced to migrate from sync to async to get a feature that doesn't call for it.

Here's a rough idea of what I'm currently thinking about. Using a generic to paramaterise the one core `Client` type, so we can thread it through request builders, avoid defining methods multiple times:

```rust
// A trait for describing a client implementation
pub trait Sender: private::Sealed {
    type Client;
    type Body;
}

// A synchronous client (using reqwest::Client)
enum SyncSender {}

impl Sender for SyncSender {
    type Client = SyncClientInner;
    type Body = SyncBody;
}

// An asynchronous client (using request::async::Client)
enum AsyncSender {}

impl Sender for AsyncSender {
    type Client = AsyncClientInner;
    type Body = AsyncBody;
}

// The client is generic over the kind of sender
struct Client<TSender> 
    where TSender: Sender
{
    inner: Sender::Client,
}

// Provide some type aliases for referencing a client easily
type SyncClient = Client<SyncSender>;
type AsyncClient = Client<AsyncSender>;

// Implementations for any sender (sync or async)
// All request builders will use this approach
impl<TSender> Client<TSender> 
    where TSender: Sender 
{
    fn request<TRequest, TBody>(&self, req: TRequest) -> RequestBuilder<TSender, RawRequestBuilder<TRequest, TBody>> 
        where TRequest: Into<HttpRequest<'static, TBody>>,
              TBody: Into<TSender::Body>
    {
        ...
    }
}

// Synchronous send implementation
impl<TRequest, TBody> RawRequestBuilder<SyncSender, TRequest, TBody>
    where TRequest: Into<HttpRequest<'static, TBody>>,
          TBody: Into<SyncSender::Body>
{
    fn send(self) -> HttpResponse {
        ...
    }
}

// Asynchronous send implementation
impl<TRequest, TBody> RawRequestBuilder<AsyncSender, TRequest, TBody>
    where TRequest: Into<HttpRequest<'static, TBody>>,
          TBody: Into<SyncSender::Body>
{
    fn send(self) -> impl Future<Item = HttpResponse, Error = HttpError> {
        ...
    }
}
```

There are some warts in there, but I'll see how the gist of this pans out. The docs will need to be clear to follow. It's already a bit confusing to find what methods are available after calling `client.search()`.
