### ISSUE TITLE
Implementing FieldType for an enum

### ISSUE THREAD

**Issue by theduke** [elastic-rs/elastic#209]
Hey there, awesome library.

How would I go about implementing FieldType for something like this:

```rust

enum SomeEnum {
  A,
  B,
  Other(String),
}

#[derive(ElasticType)]
struct Doc {
  id: String,
  something: SomeEnum,
}
```

SomeEnum should map to a keyword or just a string/text.

An example would really be appreciated here.

**Comment by KodrAus** [comment]
Hi @theduke!

All you need to do is implement `KeywordFieldType` for `SomeEnum` and it'll be mapped as a `keyword`. There's an example buried in the [account sample](https://github.com/elastic-rs/elastic/blob/master/elastic/examples/account_sample/src/model/account.rs#L60) where the `Gender` enum is mapped to a keyword with a default mapping. I'll open an issue to add some dedicated examples of using type mapping with enums.

If you have any other questions or feedback please don't hesitate to ask!

**Comment by theduke** [comment]
Cheers, I'll try it out later today and then close this if all works out.

**Comment by theduke** [comment]
Thanks for the quick help, got it working now.
