### ISSUE TITLE
Panic in typed.rs example

### ISSUE THREAD

**Issue by outkaj** [elastic-rs/elastic#221]
As discussed in #218. 

When running the `typed.rs` example, I receive the following error: 

```
thread 'main' panicked at 'Box<Any>', main.rs:81:18
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The full backtrace output is as follows:

```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:610
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
   6: rs_es_elastic::ensure_indexed
             at ./main.rs:81
   7: rs_es_elastic::main
             at ./main.rs:45
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  10: main
  11: __libc_start_main
  12: _start
```

As in the previous issue, the only change I have made to the example is adding the base URL for my own cluster using the base_url() function.

**Comment by KodrAus** [comment]
Ok this is mostly my bad. I suspect the error is the same as in #218, but the sample was panicking incorrectly with the error and not reporting the actual problem. I've [fixed this up](https://github.com/elastic-rs/elastic/pull/220/commits/1bb404d4b17cfd2dc096fbb780a5397e973f237a) in the logging PR.

**Comment by outkaj** [comment]
As per my comment in #218, I think this is due to my improper configuration of the authentication for the cluster with `elastic`. Once it is set up properly, I'll test this example again and let you know if I still receive the above error!

**Comment by outkaj** [comment]
I no longer receive the error now that my authentication is configured correctly, so this issue can be closed. Thanks again for all your help!

**Comment by KodrAus** [comment]
Thanks @outkaj. Thanks again for reporting this. I've got a lot of work ahead to make error messages more helpful.

If you run into any other issues or have other feedback please don't hesitate to open more issues.

**Comment by outkaj** [comment]
Hi @KodrAus, no need to re-open this, but I wanted to tell you that [this tutorial](https://qbox.io/blog/user-friendly-elasticsearch-queries-with-rust-and-elastic), now published, was the reason for my questions last week. I thought you might like to see it. Thanks again for all your help!

**Comment by KodrAus** [comment]
Thanks for looping back @outkaj! I saw the article on reddit, it looks great. Thanks for putting it together :)

**Comment by outkaj** [comment]
Oh nice, I didn't realize they were getting shared on Reddit!  And you're welcome!
