### ISSUE TITLE
Idea: Trait for structs in order to support Bulk Inserts

### ISSUE THREAD

**Issue by stephanbuys** [elastic-rs/elastic#248]
Add a Trait, perhaps `BulkInsertable` that will return `index`, `id` and `type` information needed so that bulk objects can be added to a `Vec` and have the client automatically "package" the data for simplified bulk inserts.

**Comment by KodrAus** [comment]
Hmm this is an interesting idea. I spent a little time thinking about bulk in #208 but haven't gotten too far.

I wondering how we would go with other kinds of bulk operations, like creates, upserts, updates, and deletes. We could have a general `BulkOperation` trait that uses the same signature you proposed, and then have a wrapper type that has the action, whether it's insert, create, update etc.

But I think there's definitely a common case where you want to just insert a bunch of docs, so we could have a client method like:

```rust
client.bulk().insert(vec![
    doc 1,
    doc2,
   ...
]).send();
```

Where `.insert` accepts any `T: BulkOperation` and wraps them up in the wrapper type using the right action.

This might actually be exactly what you were proposing. What do you think?

**Comment by stephanbuys** [comment]
I like the `BulkOperation` idea, and the proposed interface <- yup, pretty much what I was thinking, just better :-) The contract could be pretty simple, `id()`, `type()`, and `index()` returning the appropriate values, should be generalisable for the other operations you mentioned. 
We could also implement `Deserialize` (on the trait? not sure if that would work, or wherever appropriate), to make it nice and snappy. My test code is littered with `format!` macros, definitely not optimal.
