### ISSUE TITLE
Is `elastic_reqwest` pulling its weight?

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic#264]
I'm working on support for cluster sniffing in #243 and am finding myself wanting our better response building in `elastic`. It feels like `elastic_reqwest` isn't really pulling its weight anymore.

I think we should merge `elastic_reqwest` into `elastic`, and keep a nice separation of the low-level client details from the high-level builders. It'll save some boilerplate too.

I'm interested in any feedback anyone else has here. It's a move towards something more opinionated than what we have now, but I feel like as an abstraction `elastic_reqwest` isn't really offering too much.

**Comment by KodrAus** [comment]
What do you think @stephanbuys?

**Comment by KodrAus** [comment]
I've started playing with this in the [node-sniffer](https://github.com/elastic-rs/elastic/tree/feat/node-sniffer) branch.

The idea is that we should be able to use the same low-level `Sender` trait for connection pooling as we do for making other client requests. I think with a bit of effort this could work out quite nicely.

**Comment by stephanbuys** [comment]
Hi, I had a look and I fully agree, you approach on the load-balanced Async client is almost certainly the direction this library should take. Dragging the reqwest client forward seems unnecessary, while this lib is pre 1.0 you should be brutal (thinking Rust's own journey to 1.0).
From what I've seen the API still stays natural and isn't a massive departure (or increase of complexity) over reqwest, which is another huge plus.

**Comment by KodrAus** [comment]
Ok, the contents of the old `elastic_reqwest` crate are now in a new `client::sender` module in `elastic`. It's sitting  in the `vNext` branch now and will be part of the next breaking release.
