### ISSUE TITLE
Creates deadlock/eternal loop in cargo

### ISSUE THREAD

**Issue by zaibacu** [elastic-rs/elastic#283]
By adding Elastic dependency, whole cargo process breaks

```
~/.cargo/bin/cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
```
Runs forever. Removing this dependency, everything starts working fine

**Comment by KodrAus** [comment]
Hi @zaibacu, that's really strange... I just gave this a check on my OSX machine with the latest `stable` toolchain and it seems ok. Do you mind including the output of `rustc --version` and `cargo --version`? What does your `Cargo.toml` look like?

I think `cargo` usually hangs updating the registry if there are circular dependencies somewhere.

**Comment by zaibacu** [comment]
```
cargo 0.23.0 (61fa02415 2017-11-22)
rustc 1.22.1 (05e2e1c41 2017-11-22)
```

Cargo.toml
```
[dependencies]
meowth_lib = { path = "lib" }

time = "0.1.38"
log = "0.3"
env_logger = "0.4.3"
yaml-rust = "0.4.0"
getopts = "0.2.15"
hostname = "0.1.3"

zmq = "0.8.2"
statsd = "0.10.0"

elastic = "*"
```

(Linked lib compiles fine on it's own)

Adding/removing `elastic = "*"` causes deadlock.

**Comment by KodrAus** [comment]
Ah I see, it's probably the same issue that's causing your [`meowth` build to error](https://travis-ci.org/CodersOfTheNight/meowth/jobs/243129848) then? Let me take a look at it and see if I can figure out what's going on.

**Comment by KodrAus** [comment]
Ok it looks like the `elastic_derive` and `elastic` combination is causing a cycle in the dependency graph. That's not good!

I'll do some more digging and get this fixed up.

**Comment by zaibacu** [comment]
Awesome, came into similar conclussion. And it seems like this issue was there for quite a long time :) Don't know why others aren't impacted

**Comment by KodrAus** [comment]
Hmm I'm not sure either, but it looks like I didn't pick it up in CI here because it goes away when using paths in the dependencies.

**Comment by KodrAus** [comment]
Looks like if I specify a version for at least `elastic` besides `*`, like `elastic = "0.20"` it can resolve the dependency graph. Does this work for you?

**Comment by zaibacu** [comment]
Getting 

```
error: failed to select a version for `quick-error` (required by `elastic_responses`):
all possible versions conflict with previously selected versions of `quick-error`
  version 1.2.1 in use by quick-error v1.2.1
  possible versions to select: 1.1.0
```

I guess I need to tweak some versions

**Comment by KodrAus** [comment]
That's my bad. Looks like I've been a bit too tight with the version range for `quick-error`. I really only need `~1`.

I'm still looking into that deadlock, but will take a quick look through the version ranges `elastic` uses and see if any others are overly tight.

**Comment by zaibacu** [comment]
With version `v0.20.6` it seems to work 👍

**Comment by KodrAus** [comment]
Cool. I'll keep this open as a bug until I figure out what that infinite loop is about. That shouldn't happen.

**Comment by KodrAus** [comment]
It's been a while and it looks like Cargo has managed to sort itself out now, so `*` version bounds for `elastic` and `elastic_derive` won't cause an infinite loop in Cargo anymore.
