### ISSUE TITLE
Consider Migrating to `Failure` crate

### ISSUE THREAD

**Issue by stephanbuys** [elastic-rs/elastic#290]
I had an opportunity to play with the `failure` crate a couple of weeks ago and was thoroughly impressed. I believe it would be a worthwhile exercise pre 1.x to migrate to it.

**Comment by KodrAus** [comment]
I absolutely agree :+1: thanks for bringing this up! Instead of attempting to translate errors from one type to another we can just wrap them with `Context`s and reduce a lot of boilerplate and leaking of error variants.

**Comment by KodrAus** [comment]
This would also be a bit nicer for adding the correlation id to errors coming out of the `Sender` machinery and getting the `Send + Sync` bounds consistent. Overall it should be a big win.

**Comment by mwilliammyers** [comment]
I am fairly new to Rust and the whole ecosystem, but it seems like there is [somewhat](https://github.com/rust-lang-nursery/failure/issues/209) of a [debate](https://github.com/rust-lang-nursery/failure/issues/287) about the future of `failure` especially considering that fixing `std::error::Error` has recently seen some new momentum (it looks like). 

Should we just use the downcasting support that just landed in 1.33 or go forward with Failure?

In the meantime, I opened #340 and will continue to improve errors as I run into them.

**Comment by KodrAus** [comment]
@mwilliammyers Yeh the state of the world is a little different now. `failure` is still a nice library for error management in applications (where you can easily `#derive(Fail)]`), but some of the holes in `std::error::Error` for libraries have been filled.

Sticking with `std::error::Error` for now seems ok. And thanks for working on improving the API errors!

**Comment by KodrAus** [comment]
We now use the new `error::Error` APIs for properly downcastable errors so I'll go ahead and close this one. We can open new issues for other deficiencies with the errors.
