### ISSUE TITLE
Use object type over nested type with nested structures?

### ISSUE THREAD

**Issue by AlexKornitzer** [elastic-rs/elastic#312]
Hi,

Similar to what I believe is implemented here: https://github.com/elastic-rs/elastic/issues/72. Is there a way to tell elastic-rs that I want it to auto derive the mapping yet override the type to `object` instead of `nested`?

```
#[derive(ElasticType)]
pub struct B {
    pub b: String,
}

#[derive(ElasticType)]
pub struct A {
    pub a: String,
    #[elastic(ty="object")]  <- Prefer object over nested?!
    pub b: Option<B>
}
```

Apologies if this already exists and I have just totally glossed over it. Currently when I look in the elastic mapping my nested structures are always type nested which I do not want, I do not need the nested overhead and hence need these to be type object but do not really want to create these mappings by hand. Otherwise awesome library :D

**Comment by KodrAus** [comment]
Hi @AlexKornitzer! Yeh, this is a bit of a deficiency at the moment. The `DocumentMapping` type isn't a perfect fit for how documents are actually stored in Elasticsearch. The way things work now, if you want `B` to be mapped as an `object` in `A` then we need to configure it on `B`'s mapping. So right now the best we can do is tell `B` to always be mapped as `object` when it appears in another type [by deriving `DocumentMapping` explicitly](https://docs.rs/elastic/0.20.10/elastic/types/document/index.html#override-default-mapping-properties) on `B`, and setting its `data_type` to `OBJECT_DATATYPE`.

#232 should make it more ergonomic to use a different type for documents that appear as fields in other documents, so it'll look closer to the example you posted.

**Comment by AlexKornitzer** [comment]
Ah that first link looks like what I need, still beats writing the mappings by hand :) Let me try that out, I must have glanced over it when reading the docs.

**Comment by KodrAus** [comment]
I think the mapping is all a bit buried in the docs at the moment, because the structure doesn't really make it easy to find something if you don't already know what you're looking for.

Some clearer examples at the top level would probably be helpful.

**Comment by AlexKornitzer** [comment]
No worries, the link you posted above has done what I needed. Thanks for the help, feel free to close this issue.

**Comment by KodrAus** [comment]
Thanks @AlexKornitzer! Feel free to open new issues for any other questions you have.
