### ISSUE TITLE
AsyncClient is no longer Send or Sync

### ISSUE THREAD

**Issue by GyrosOfWar** [elastic-rs/elastic#321]
It appears the `pre_send` field on the AsyncSender stops the client from being `Send` and `Sync`. Is that intentional?

This came up because until now I was able to hold a `lazy_static` AsyncClient in my application, which no longer works.

**Comment by KodrAus** [comment]
Thanks for the report! This wasn't intentional, I'll fix that up and add some tests to ensure we don't accidentally regress the bounds.
