### ISSUE TITLE
Get the document id in Hit

### ISSUE THREAD

**Issue by 2phost** [elastic-rs/elastic#323]
When I do a search I obtain  set of Hits. Each hit have the _source, however none of them have the _id automatically assigned by Elasticsearch.
I know that tipically you put your own id and a field indicating it, but this is not even recommended.

To have a good performance you have to let Elasticsearch create an id for the document. I have been working with elasticsearch since 2.1 version and it was always like that.

So my question is, how can I obtain the document id from a hit? I need it because I want to do some work with the documents and update or delete them.

**Comment by KodrAus** [comment]
Hi @2phost :wave:

It looks like we're just missing the `id` field on our hits response type. I'll fix this up.

**Comment by 2phost** [comment]
Hi @KodrAus , 

Thank you.
