### ISSUE TITLE
Examples not working ?

### ISSUE THREAD

**Issue by aesteve** [elastic-rs/elastic#328]
Hello, and thank you for the work you're providing with this library.

I tried to have it working with a very very basic example, and I can't get it working.

Here's the example : 

```rust
#[macro_use] extern crate serde_derive;
#[macro_use] extern crate elastic_derive;
use std::fs;
use elastic::prelude::*;

#[derive(ElasticType, Serialize, Deserialize, Clone, Debug)]
pub struct Stuff {
    #[elastic(id)]
    pub title: String,
    pub description: String,
}

// see: https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html
type AnyError = Box<dyn std::error::Error>;
fn index_stuff() -> Result<(), AnyError> {
    let es_client : SyncClient = SyncClientBuilder::new().build()?; // http://localhost:9200
    let stuff_index = es_client.index(Stuff::static_index()).create().send()?;
    for entry in fs::read_dir("stuffs")? {
        let file = fs::File::open(entry?.path());
        let stuff: Stuff = serde_yaml::from_reader(file?)?;
        es_client.document::<Stuff>().index(stuff).send()?;
    }
    Ok(())
}

```

Nothing fancy, just the example from the docs. 

It fails saying Stuff has no member static_index, that neither method `document` exist on client, nor method `index`, etc. etc.

Just like if I was missing a whole bunch of stuff.

Your library sounds very nice, with the macro use etc. I'd really love giving it a try, and using it.

Are the examples in master really reflecting the published version ? 
If not, I don't mind using a more recent version, but how ?

What should I do to have the examples working on my computer ?

Thank you

**Comment by KodrAus** [comment]
Hey @aesteve :wave: I've published the current `master` branch on crates.io as `0.21.0-pre.1`, so if you update your `Cargo.toml` like this then your example should start compiliing:

```toml
[dependencies.elastic]
version = "0.21.0-pre.1"

[dependencies.elastic_derive]
version = "0.21.0-pre.1"
```

Please feel free to reach out if you run into any more trouble!

**Comment by aesteve** [comment]
Working like a charm.

Thank you very much for your help.

Time to get my hands into the API. Great job.

**Comment by KodrAus** [comment]
Please feel free to open new issues if anything seems odd or unclear. There's a lot of new stuff in that release and the docs haven't quite caught up yet.
