### ISSUE TITLE
Possibility of adding `_id` and `_version` to `_source`

### ISSUE THREAD

**Issue by mwilliammyers** [elastic-rs/elastic#332]
Related to #323...

What do you think about adding `id` (`_id`) and `version` (`_version`), from e.g. the `Hit` type etc., to whatever type we are deserializing to (from `_source`) if that type has an `id` field or `version` field... 

I am fairly new to Rust so I am not sure if this is the best way to do it, but I find myself `.mapping(Foo::from)` over the `Hits` via stuff like this (minus the `.unwrap()`s):
```
#[derive(Serialize, Deserialize, GraphQLObject, ElasticType, Debug)]
pub struct Foo {
    id: String,
    version: i32,
    text: String,
}

impl From<Hit<Value>> for Foo {
    fn from(hit: Hit<Value>) -> Self {
        let doc = hit
            .document()
            .unwrap()
            .get("doc")
            .unwrap();

        Call {
            id: hit.id().to_string(),
            version: match hit.version() {
                Some(i) => i as i32,
                _ => 0,
            },
            text: doc.get("text").unwrap().to_string(),
        }
    }
}
```

It could obviously be behind some option (maybe in the `Builders` themselves?) to preserve backwards compatibility.

**Comment by KodrAus** [comment]
This is an interesting idea 🤔 But would be a little tricky to pull off using `serde`'s serialization API, since we're not actually in control of the way document types are deserialized.

**Comment by mwilliammyers** [comment]
I think it kind of deviates from ES so maybe we shouldn't?
