### ISSUE TITLE
OpenSSL requirement from reqwest

### ISSUE THREAD

**Issue by jatsrt** [elastic-rs/elastic#336]
0.21.0-pre.2

Reqwest has an optional feature to switch to "rustls-tls".  This allows much easier cross compilation.  Elastic uses reqwest, but just uses it as is, so it is pulling in hyper-tls, which requires openssl.  

I do not beleive(though I could be wrong).  That this is something that can be externally changed in cargo.  So, the question is, is it possible to enable a passthrough feature that would allow the use of elastic with rustls-tls, or to default for compatibility.

**Comment by KodrAus** [comment]
Hi @jatsrt :wave:

If you add `reqwest` as a dependency in your Cargo.toml alongside `elastic` with the `rustls-tls` feature then it should all work, but I'd also be happy to add a `rustls-tls` feature to `elastic` that enabled the same feature in its own `reqwest` dependency.

**Comment by jatsrt** [comment]
Tried that, as I already use reqwest for other purposes, didn't work.

`
[dependencies]
serde = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_derive = "1.0"
elastic = "0.21.0-pre.2"
elastic_derive = "0.21.0-pre.2"

reqwest = {version = "0.9", default_features = false, features=["rustls-tls"]}
`

**Comment by jatsrt** [comment]
unless I need to match the version exactly with "~0.9"

**Comment by jatsrt** [comment]
That's it, needs to be a precise match on the version.

**Comment by jatsrt** [comment]
OK, no that did not do the trick

```
serde = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_derive = "1.0"
elastic = "0.21.0-pre.2"
elastic_derive = "0.21.0-pre.2"

reqwest = {version = "~0.9", default_features = false, features=["rustls-tls"]}
```

**Comment by KodrAus** [comment]
Ah right, so `reqwest` uses a `default-tls` feature that we have to disable before it'll stop compiling `openssl`, in which case just adding a dependency on `reqwest` yourself won't be enough.
