### ISSUE TITLE
Change default document type from `doc` to `_doc`

### ISSUE THREAD

**Issue by mwilliammyers** [elastic-rs/elastic#337]
Per [schedule for removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types), the preferred document type name is now `_doc`.  Should we change the default to `_doc`?

Would I have to change anything that you know of besides the declaration [here](https://github.com/elastic-rs/elastic/blob/f16a3720dba6a940c804650e463b3cd25c614a88/src/elastic/src/types.rs#L278) and some tests?

**Comment by mwilliammyers** [comment]
So all I did was change that one line and all of the tests are passing... If that is it, I can open a PR.

**Comment by KodrAus** [comment]
@mwilliammyers I ended up with `doc` over `_doc` because Elasticsearch versions prior to `6.2` don't actually accept that leading `_`.

Hmm, I think we'll actually need to shift that `DEFAULT_TYPE` constant into the `elastic_types` crate and re-export it from there so that generated mappings can use it as well.

**Comment by KodrAus** [comment]
I opened a PR to make that constant more useful, it was a bit of a missed opportunity to begin with to make sure we have one place where the default type name is defined.

If we only want to support Elasticsearch 6.2+ then I'm happy for us to use `_doc` instead of `doc`.

**Comment by mwilliammyers** [comment]
Cool, thanks!

What are your thoughts on versions to support?

**Comment by KodrAus** [comment]
I think maintaining support for the highest point-release of the Elasticsearch major version we support without breakage should do for the time being. If we need to make any breaking changes to support a point release then we can bundle that up into a new breaking version of this library.

**Comment by mwilliammyers** [comment]
Fixed in #356.
