### ISSUE TITLE
Mapping to a keyword type without a subfield

### ISSUE THREAD

**Issue by mwilliammyers** [elastic-rs/elastic#342]
This might be really easy but I can't figure it out.

The following:

```rust
struct ID(String);

impl KeywordFieldType<DefaultKeywordMapping> for ID {}
```

maps to:
```json
"id": {
    "type": "text",
    "fields": {
        "keyword": {
            "type": "keyword",
            "ignore_above": 256
        }
    }
}
```

I want it to map to:
```json
"id": {
    "type": "keyword"
}
```

so that you don't have to specify `id.keyword` when searching...

What am I missing?

For good measure I have also tried:
```rust

struct IdMapping;

impl KeywordMapping for IdMapping {
    fn analyzer() -> Option<&'static str> {
        Some("keyword")
    }
}

impl KeywordFieldType<IdMapping> for ID {}
```

**Comment by mwilliammyers** [comment]
FYI this isn't just for newtypes. It also didn't work when I specified the mapping type using a field attribute. I saw on [this](https://github.com/elastic-rs/elastic/blob/4f841ab48799ed38032c88b37232a7247e5f32e4/src/types_derive_internals/src/elastic_type/mod.rs#L96) line that field attributes are supported, so maybe #232 is at least partially supported?

**Comment by KodrAus** [comment]
Thanks for the report! This sure doesn't look right, I'll check it out :+1:

**Comment by mwilliammyers** [comment]
Thanks! I took a look at it but I don't think I know the code well enough yet to figure out what is going on...

**Comment by KodrAus** [comment]
Hi @mwilliammyers, I haven't been able to  reproduce this one just yet so I must be missing something... Could you possibly share some more details about where you're getting your json mapping from?

At least the following example:

```rust
use elastic::prelude::*;

#[macro_use]
extern crate elastic_derive;

#[macro_use]
extern crate serde_derive;

#[derive(Serialize, ElasticType)]
pub struct Document {
    id: Id,
}

#[derive(Serialize)]
pub struct Id(String);

impl KeywordFieldType<DefaultKeywordMapping> for Id {}

fn main() {
    let json = serde_json::to_string(&Document::index_mapping()).unwrap();

    println!("{}", json);
}
```

produces:

```
{"properties":{"id":{"type":"keyword"}}}
```

which is what we'd expect.

**Comment by mwilliammyers** [comment]
Ok, I finally got some time to dig into this more. Here is what I have discovered so far:

```rust
use std::borrow::Cow;

use elastic::prelude::*;
use elastic_derive::ElasticType;
use serde::{Deserialize, Serialize};
use serde_json::{self, Value as JsonValue};

#[derive(Serialize, Deserialize)]
struct Id(String);

impl KeywordFieldType<DefaultKeywordMapping> for Id {}

#[derive(Serialize, ElasticType)]
struct Document {
    #[elastic(id)]
    id: Id,
}

impl<'a> Into<Cow<'a, str>> for &'a Id {
    fn into(self) -> Cow<'a, str> {
        Cow::from(&self.0)
    }
}

fn main() {
    let json = serde_json::to_string(&Document::index_mapping()).unwrap();
    println!("{}\n", json);

    let doc = Document {
        id: Id("1".to_string()),
    };

    let client = SyncClientBuilder::new().build().unwrap();

    let response = client.document().index(doc).send().unwrap();
    println!("{:#?}\n", response);

    let mapping = client
        .request(IndicesGetMappingRequest::for_index("document"))
        .send()
        .unwrap()
        .into_response::<JsonValue>()
        .unwrap();

    println!("{}", serde_json::to_string_pretty(&mapping).unwrap());
}
```

outputs:
```json
{"properties":{"id":{"type":"keyword"}}}
```
```
IndexResponse {
    index: "document",
    ty: "doc",
    id: "1",
    version: Some(
        1,
    ),
    result: Created,
    shards: Shards {
        total: 2,
        successful: 1,
        failed: 0,
    },
}
```

```json
{
  "document": {
    "mappings": {
      "doc": {
        "properties": {
          "id": {
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            },
            "type": "text"
          }
        }
      }
    }
  }
}
```

pretty sure it is due to the `impl Cow`, which is necessary to use it as an Elastic ID.

**Comment by mwilliammyers** [comment]
I guess I should also add I have tested it (with the same behavior) on:
```json
{
  "number": "6.8.0",
  "build_flavor": "default",
  "build_type": "docker",
  "build_hash": "65b6179",
  "build_date": "2019-05-15T20:06:13.172855Z",
  "build_snapshot": false,
  "lucene_version": "7.7.0",
  "minimum_wire_compatibility_version": "5.6.0",
  "minimum_index_compatibility_version": "5.0.0"
}
```

```json
{
  "number": "6.0.0",
  "build_hash": "8f0685b",
  "build_date": "2017-11-10T18:41:22.859Z",
  "build_snapshot": false,
  "lucene_version": "7.0.1",
  "minimum_wire_compatibility_version": "5.6.0",
  "minimum_index_compatibility_version": "5.0.0"
}
```

**Comment by mwilliammyers** [comment]
Oops... It looks like this is all a result of [dynamic field mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html). 

I don't know why, but I assumed the types I specified would override the dynamic field mappings ES does... Then it dawned on me that the types I specify/this library automatically derives only apply if you manually create the index/update the index's mapping (via `.index(...).create()` or `put_mapping()` etc.)

I will just have to use smarter/more customized [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) or add some logic when my server fires up to create the indices (if they don't exist already) and then create/update the mappings so my Rust data types stay in sync with ES... I thought I would be free from creating tables with column types etc. when but alas that was too good to be true haha

I guess we can close this, or maybe other people might assume the same things I did and we should mention it in the docs somewhere?

**Comment by KodrAus** [comment]
Ah right, that is a bit of a footgun where mappings we specify in Rust won't find their way to Elasticsearch unless we explicitly send them.

I wonder if other clients address this somehow.

**Comment by mwilliammyers** [comment]
Yeah I was trying to think of a way to handle it but I don't think there is a good way.

Maybe I'll open a PR to address it briefly in the docs? I feel really stupid for not thinking of it but at the same time, I do feel like I was being very specific and intentional with what types I chose which lead me to erroneously believe they would just magically end up in Elasticsearch.
