### ISSUE TITLE
bulk insert operation wraps every document in 'doc'

### ISSUE THREAD

**Issue by bauto17** [elastic-rs/elastic#346]
hi, I have an issue, I am trying to use bulk insert and my document's body is always wrapped by a Doc struct
![image](https://user-images.githubusercontent.com/8044785/56328000-81819600-6142-11e9-823c-4b1ce314ffe0.png)

According to the official documentation, bulk insert operation must not provide a 'doc' wrapper, I's only necessary for updating operations.
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-bulk.html
{ "index" : { "_index" : "test", "_type" : "_doc", "_id" : "1" } }
{ "field1" : "value1" }

**Comment by KodrAus** [comment]
Hi @bauto17 :wave:

Could you share which version of the client you're using? I believe we [fixed this up recently](https://github.com/elastic-rs/elastic/commit/ad941241f781a13f35c336ddd2d495b87b6247a8), so you might just need to update to the current `0.21.0-pre.3` release.

**Comment by bauto17** [comment]
It's still in use in BulkRawOperation struct in this path src/elastic/src/client/requests/bulk/operation.rs

**Comment by KodrAus** [comment]
Ah that's my bad! Thanks for the report @bauto17. I've created a PR to fix this up and will release it as `0.21.0-pre.4`.
