### ISSUE TITLE
Geo Dependency Updates

### ISSUE THREAD

**Issue by MrArnoldPalmer** [elastic-rs/elastic#357]
There are some small changes to (de)serialization needed to be able to update the geo library dependencies. I can make a PR if interested?

**Comment by KodrAus** [comment]
Thanks @MrArnoldPalmer that would be much appreciated! Please reach out if you run into any troubles. We're currently working on pre-releases so breaking changes are ok to make.

**Comment by MrArnoldPalmer** [comment]
Sorry I put this project away for a minute. I had it compiling but need to fix some tests. Hoping to get into it soon. Will reach out with any questions.

**Comment by KodrAus** [comment]
No problems, thanks for working on this @MrArnoldPalmer!

**Comment by KodrAus** [comment]
Hi @MrArnoldPalmer :wave:

I've updated our `geo` dependencies in a round of refactoring that will be available in the next preview release. Thanks for pointing this out!

**Comment by MrArnoldPalmer** [comment]
Awesome! Looking forward to the next preview!
