### ISSUE TITLE
Error Parsing Response

### ISSUE THREAD

**Issue by taylorjdawson** [elastic-rs/elastic#361]
I am using elasticsearch 7.1.0 so there could be [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_search_changes) in the response causing the issue. 
```
Elasticsearch Request: 
  correlation_id: '5a7f39d3-40bc-406a-ae79-cea67d55b5a7', 
  path: '/line/_search'
Elasticsearch Response:
  correlation_id: '5a7f39d3-40bc-406a-ae79-cea67d55b5a7',
  status: '200 OK'
thread '<unnamed>' panicked at 'Client Error: 
  Client(ClientError { inner: Error(Response(200), 
  State { 
    next_error: Some(Parse(ParseError 
      { inner: Error("invalid type: map, expected u64", line: 1, column: 105) }))
```
As you can see the request succeeds but then it fails to parse the response.

Code --> 
```
    let client = SyncClientBuilder::new()
        .static_node("http://localhost:9200")
        .build();

    let client = match client {
        Ok(client) => {
            client
        },
        Err(e) => {
            panic!("Error building client {:?}", e)
        }
    };

    let query_string = json!({
            "query" : {
                "term" : { "line" : "some query" }
            }
    });

    let req = {
        let body = query_string;
        SearchRequest::for_index_ty("quotes", "", body)
    };

    let response = client.request(req)
        .send().unwrap()
        .into_response::<SearchResponse<Value>>();

    match response {
        Ok(response) => {
            
            for hit in response.hits() {
                println!("{:?}", hit);
            }
            response
        },
        Err(Error::Api(e)) => {
           
            panic!("API Error: {:?}", e)
        },
        Err(e) => {
            
            panic!("Client Error: {:?}", e)
        }
    }
```
Also please excuse the bad code I am new to Rust and this may very well be user error.

Let me know if you need anymore info and thanks for looking into it!

**Comment by KodrAus** [comment]
Thanks for the report @taylorjdawson!

We’re still working on 7.0 support, so it is definitely possible that our response types aren’t lining up anymore. I’ll take a look and let you know I find :+1:

Also, just an aside you should be able to use some more convenient methods to make your search request:

```
let res = client.search::<Value>()
    .index(“quotes”)
    .body(query_string)
    .send()
```

**Comment by taylorjdawson** [comment]
Awesome, thanks!
Yeah I was using that to pinpoint the error. For instance, this does work:
```
    let req = {
        let body = query_string;
        SearchRequest::for_index("quotes", body)
    };

    let mut response = client.request(req)
        .send().unwrap().into_raw();

    let mut body = String::new();
    response.read_to_string(&mut body);

    println!("{}", body);
```

So it is the `into_response` function that is causing the issue. If someone could point me to where the code parses the elasticsearch response, I could look into it!

**Comment by flaper87** [comment]
FWIW, I'm hitting this issue too. Running Elasticsearch `7`. 

Just like @taylorjdawson , I'd be happy to help to fix this issue if you point me to the right place where this may be happening.

I see it also after indexing data with both (bulk and simple inserts): `client.bulk().extend(ops).send()` and `client.document().index(doc).send()?;`

**Comment by KodrAus** [comment]
Hey all, I've fixed this up on `master` where we target `7.x` so it'll be available in the next preview. It looks like the format for the `total` field changed.

**Comment by flaper87** [comment]
@KodrAus thanks a bunch, you rock!
