### ISSUE TITLE
HitsTotal Mapping Error

### ISSUE THREAD

**Issue by jatsrt** [elastic-rs/elastic#373]
Not sure what the change is, but getting this in preview 5/master, looks like the mapping changed for the type and is not correct:
```
ClientError {
        inner: Error(
            Response(
                200,
            ),
            State {
                next_error: Some(
                    Parse(
                        ParseError {
                            inner: Error("invalid type: number, expected struct HitsTotal", line: 1, column: 107),
                        },
                    ),
                ),
                backtrace: None,
            },
        ),
```

**Comment by jatsrt** [comment]
Looks like a 7.x AIP change that's not compatible with 6.x

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-track-total-hits.html

**Comment by jatsrt** [comment]
Will close this for now, but something to think on.  With elasticsearch you generally have two major versions in play at any given time.  Right now v 6.x is "production" for most/many organizations, while 7.x is the emerging version.  

Example of how this is managed from another project: https://olivere.github.io/elastic/

Not easy for sure.

**Comment by GopherJ** [comment]
@jatsrt hello, so if I still use elasticsearch@5.6.16, is there a way to use `elastic-rs`?

**Comment by jatsrt** [comment]
Not currently as it is only kept up to date with the latest elastic mappings, which is currently at 7.0.
I personally am still on 6.x and have a branch I maintain where I fix what is needed to keep it working right.
