### ISSUE TITLE
Do the RequestParams for params_fluent() need to be 'static?

### ISSUE THREAD

**Issue by mwilliammyers** [elastic-rs/elastic#379]
Currently the [RequestParams](https://github.com/elastic-rs/elastic/blob/0f90521cf03304f2bfa870a8511d8cfc4f69d18f/src/elastic/src/client/requests/mod.rs#L169) parameter to the `.params_fluent()` closure is `'static`. Does it need to be? I am trying to let a user set `refresh` via an API call and that makes it really tricky...

I tried using the regular `.params()` method but then I have to pass in a URL...

**Comment by KodrAus** [comment]
Ah yes, this is a limitation of the way the request parameters use builders right now. I'd like to just throw out the whole `fluent_builder` thing that captures closures and just update a set of request parameters internally, then we won't need for them to be static.

**Comment by mwilliammyers** [comment]
Ahhh... Then could we make the Elasticsearch host URL available via `RequestParams` or just get rid of it and use `PreRequestParams` everywhere? I haven't really dug into what would be required to do that...

**Comment by mwilliammyers** [comment]
Closing in favor of #372
