### ISSUE TITLE
Consider bumping `nom` version

### ISSUE THREAD

**Issue by brndnmtthws** [elastic-rs/elastic#383]
I recently ran into this problem:

https://users.rust-lang.org/t/a-dependency-compiles-on-its-own-but-does-not-compile-as-dependency-lettre-nom/18097/6

tl;dr nom has this weird opt-out flag that breaks compatibility if you depend on 2 crates with different feature flags. It's a pretty annoying bug with how Rust handles dependencies.

As a temporary solution I just bumped the `nom` version from 2 -> 3 and the issue went away because the other crate ([`procinfo`](https://github.com/danburkert/procinfo-rs/blob/master/Cargo.toml#L22)) depends on `nom = "0.2"`.

There are 2 possibilities for resolving this:

1. Upgrade the `nom` dependency
2. Use verbose-errors (this seems less preferable)

Thoughts?

**Comment by KodrAus** [comment]
Hi @brndnmtthws :wave:

We don't use `nom` as a public dependency so bumping it shouldn't be a problem.
